"""Generate the MkDocs playbook card catalog from Playbooks/*/README.md."""

from __future__ import annotations

import html
import re
from pathlib import Path
from urllib.parse import quote


REPO_ROOT = Path(__file__).resolve().parents[1]
PLAYBOOKS_DIR = REPO_ROOT / "Playbooks"
OUTPUT_PATH = REPO_ROOT / "Cookbooks" / "docs" / "playbooks.md"
GITHUB_PLAYBOOK_ROOT = "https://github.com/ciscoAISCG/webex-cx-ai/tree/main/Playbooks"


def clean_markdown(text: str) -> str:
    """Convert a short README sentence into safe plain text."""
    text = re.sub(r"!\[([^]]*)\]\([^)]*\)", r"\1", text)
    text = re.sub(r"\[([^]]+)\]\([^)]*\)", r"\1", text)
    text = re.sub(r"[`*_]", "", text)
    return re.sub(r"\s+", " ", text).strip()


def read_title_and_description(readme_path: Path, folder_name: str) -> tuple[str, str]:
    lines = readme_path.read_text(encoding="utf-8").splitlines()
    title = folder_name.replace("_", " ").replace("-", " ").title()
    description_lines: list[str] = []
    title_found = False

    for line in lines:
        match = re.match(r"^#\s+(.+?)\s*$", line)
        if match and not title_found:
            title = clean_markdown(match.group(1))
            title = re.sub(r"\s+(?:-|—)\s+Webex Contact Center.*$", "", title, flags=re.I)
            title_found = True
            continue

        if not title_found:
            continue

        stripped = line.strip()
        if not stripped:
            if description_lines:
                break
            continue
        if stripped.startswith(("#", "!", "---", "```", "|", "- ", "* ")):
            if description_lines:
                break
            continue

        description_lines.append(clean_markdown(stripped))
        if len(" ".join(description_lines)) >= 320:
            break

    description = " ".join(description_lines)
    if not description:
        description = "Reusable Webex CX AI implementation pattern and supporting assets."
    return title, description[:320].rstrip(" .,;") + "."


def card(folder: Path) -> str:
    title, description = read_title_and_description(folder / "README.md", folder.name)
    safe_title = html.escape(title)
    safe_description = html.escape(description)
    link = f"{GITHUB_PLAYBOOK_ROOT}/{quote(folder.name)}"
    return f'''  <a class="playbook-card" href="{link}" target="_blank" rel="noopener">
    <span class="playbook-card__eyebrow">Playbook</span>
    <h2>{safe_title}</h2>
    <p>{safe_description}</p>
    <span class="playbook-card__link">Open playbook on GitHub →</span>
  </a>'''


def generate() -> None:
    folders = sorted(
        (
            folder
            for folder in PLAYBOOKS_DIR.iterdir()
            if folder.is_dir() and not folder.name.startswith(".") and (folder / "README.md").exists()
        ),
        key=lambda path: path.name.lower(),
    )
    cards = "\n\n".join(card(folder) for folder in folders)
    body = f'''<!-- Generated by scripts/generate_playbook_catalog.py. Edit the playbook READMEs instead. -->
# Playbooks

Reusable, implementation-oriented Webex CX AI patterns. Each card opens the complete playbook in the AI SCG GitHub repository.

<div class="playbook-grid">
{cards}
</div>
'''
    OUTPUT_PATH.write_text(body, encoding="utf-8", newline="\n")
    print(f"Generated {OUTPUT_PATH} with {len(folders)} playbook cards.")


if __name__ == "__main__":
    generate()
